export let dataScheme = {
    "all":"全部数据",
    "total_commission": "总提成",
    "order_commission": "总接单提成",
    "reward_commission": "总打赏提成",
    "add_clock_commission": "总加钟提成",
    "order_accept_cnt": "总接单量",
    "order_accept_price": "总接单金额",
    "order_complete_cnt": "成交量",
    "order_complete_price": "成交金额",
    "order_refund_cnt": "退单量",
    "order_refund_price": "退单金额",
    "order_reward_cnt": "打赏量",
    "order_reward_price": "打赏金额",
    "add_clock_cnt": "加钟量",
    "add_clock_price": "加钟金额",
    "order_reject_cnt": "拒单量",
    "order_reject_price": "拒单金额",
    "travel_price": "打车金额",
}